version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev"]
    restart: unless-stopped
    volumes:
    - ./themes/tailwind-example/:/opt/keycloak/themes/tailwind-example/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8443:8443
      - 8080:8080
